spring:
  data:
    mongodb:
      uri: mongodb+srv://utkarshdubey0242:ZU6CXN41NYhNt1wk@myjournalapp.ajczvxd.mongodb.net/?retryWrites=true&w=majority&appName=MyJournalApp
      database: journaldb
      auto-index-creation: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: utkarshdubey0242@gmail.com
    password: tmon dikt bqqz aori
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8080
  servlet:
    context-path: /journal