spring:
  profiles:
    active: dev

logging:
  level:
    com:
      utkarsh:
        journalApp: DEBUG
    org.springframework.mail: DEBUG  # Added for email debugging

weather:
  api:
    key: ea814d33c2ab270b5ef17f34e000dceb