spring:
  data:
    mongodb:
      uri: mongodb+srv://utkarshdubey0242:ZU6CXN41NYhNt1wk@myjournalapp.ajczvxd.mongodb.net/?retryWrites=true&w=majority&appName=MyJournalApp
      database: journaldb
      auto-index-creation: true

server:
  port: 8080
  servlet:
    context-path: /journal
